### ISSUE TITLE
prevent silently failing when a config.yml key is misspelt

### ISSUE THREAD

**Issue by ssteffl** [ucb-bar/hammer#526] opened 2019-10-01 15:37 UTC
hammer currently defaults silently to the defaults.yml. it would be nice if the hammer-ir used a schema validation like the tech-plugin.json

**Comment by edwardcwang** [comment] 2019-10-01 17:04
Duplicate of #160? This is harder to do since a key like `technology.abc123.foobar` is "valid" since it's meant to be in an "extension namespace"

**Comment by ssteffl** [comment] 2019-10-01 17:54
yep, duplicate

**Closed** 2019-10-01 17:54 UTC
Labels: enhancement, low priority

**Comment by jwright6323** [comment] 2019-10-01 17:58
Probably more accurately #385, which is also linked to #160.
