### ISSUE TITLE
Regenerate `.json` with new `.yml` config

### ISSUE THREAD

**Issue by abejgonzalez** [ucb-bar/hammer#491] opened 2019-08-12 17:57 UTC
Please correct me if I am wrong on any of the points below.

In the HAMMER makefile build flow, if you change the `.yml` to something new to affect only PAR, you must rerun SYN to get a new `par-input.json`. For ex. changing the `sdc` parameters. Maybe there should be a way to regenerate the `.json` file without having to rerun synth? This would allow you to avoid having to patch the `redo-par` step with `HAMMER_REDO_ARGS`.

**Comment by jwright6323** [comment] 2019-08-12 18:11
This is a duplicate of #314

**Closed by jwright6323** 2019-08-12 18:11 UTC
