### ISSUE TITLE
Cannot override drc/lvs inputs for hierarchical subblocks in separate input yaml

### ISSUE THREAD

**Issue by colinschmidt** [ucb-bar/hammer#472] opened 2019-06-27 07:40 UTC
makes using the generated makefile hard.

**Comment by colinschmidt** [comment] 2019-06-27 07:45
Apparently hammer has a preference for json over yaml...

**Comment by harrisonliew** [comment] 2019-11-07 19:10
The preference was fixed by #535, and the hierarchical issue seems like a duplicate of #401, therefore I'm closing this.

**Closed by harrisonliew** 2019-11-07 19:10 UTC
